name: location_geolocator
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  data:
    path: ../../core/data/
  geolocator: ^11.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
